In [1]:
import pandas as pd 
import sqlite3

In [2]:
conn = sqlite3.connect("cached_data/cached_data.db")
pd.read_sql("SELECT name, type FROM sqlite_master", conn)

                name   type
0    dpm_produit_raw  table
1          table_rcp  table
2  idx_table_rcp_cis  index

In [5]:
df_rcp = pd.read_sql("SELECT * FROM table_rcp", conn)
df_rcp[df_rcp["denomination"]=="AUGMENTIN 1 g/125 mg, poudre pour suspension buvable en sachet-dose (rapport amoxicilline/acide clavulanique : 8/1)"]

,code_cis,denomination,substance
2134,66053338,"AUGMENTIN 1 g/125 mg, poudre pour suspension b...",AMOXICILLINE TRIHYDRATÉE
2135,66053338,"AUGMENTIN 1 g/125 mg, poudre pour suspension b...",CLAVULANATE DE POTASSIUM

In [4]:
df_dpm = pd.read_sql("SELECT * FROM dpm_produit_raw", conn)
df_dpm.head()

,nom,dosage,forme,presentation,dci,classe,sous_classe,laboratoire,amm,date_amm,conditionnement_primaire,specification_conditionnement_primaire,tableau,duree_conservation,indications,g_p_b,veic
0,5-FLUOROURACIL,250 MG,Solution injectable,B/5/5ML,FLUOROURACILE,ANTINEOPLASIQUES ET IMMUNOMODULATEURS,ANTINEOPLASIQUES,EBEWE Pharma,6943091H,2001-01-20 00:00:00,Ampoule,en verre,A,24,- Adénocarcinomes digestifs évolués;\r- Cancer...,Générique,Vital
1,5-FLUOROURACILE EBEWE,1000 mg/20 ml,Solution injectable pour perfusion,B/1/20 ml,FLUOROURACILE,ANTINEOPLASIQUES ET IMMUNOMODULATEURS,ANTINEOPLASIQUES,EBEWE Pharma,6943093H,2012-04-30 00:00:00,Flacon,en verre incolore de type I + bouchon bromobut...,A,24,- Adénocarcinomes digestifs évolués;\r- Cancer...,Générique,Vital
2,5-FLUOROURACILE EBEWE,500 mg/10 ml,Solution injectable pour perfusion,B/5/10 ml,FLUOROURACILE,ANTINEOPLASIQUES ET IMMUNOMODULATEURS,ANTINEOPLASIQUES,EBEWE Pharma,6943092H,2012-04-30 00:00:00,Flacon,en verre incolore de type I + bouchon bromobut...,A,24,- Adénocarcinomes digestifs évolués;\r- Cancer...,Générique,Vital
3,ABBOTICINE,200 MG,Poudre pour suspension orale,FL/60ML,ERYTHROMYCINE,ANTIINFECTIEUX GENERAUX A USAGE SYSTEMIQUE,ANTIBACTERIENS (USAGE SYSTEMIQUE),ADWYA,9043061,1990-12-19 00:00:00,Flacon,en verre ambre,A,48,INFECTIONS DUES AUX GERMES SENSIBLES NOTAMMENT...,Princeps,Essentiel
4,ABEVMY,400 mg(25mg/ml),Solution à diluer pour perfusion,B/1FL/16ml,BEVACIZUMAB,ANTINEOPLASIQUES ET IMMUNOMODULATEURS,ANTINEOPLASIQUES,MYLAN PHARMACEUTICALS PRIVATE LIMITED,20343022H,2021-09-06 00:00:00,Flacon,en verrede type I,A,24,Cancer métastatique du colon ou du rectum\r- A...,Biosimilaire,Vital